DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 16
  TEST:
    BATCH_SIZE: 256
  NUM_WORKERS: 16

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.28
  MAX_EPOCH: 25
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 0
  WARMUP_TYPE: "linear"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  LWEIB:
    TEXT_CTX_INIT: "a photo of a"
    ADAPTER_START: 1
    ADAPTER_END: 12
    ADAPTER_SCALE: 0.025
    ADAPTER_SCALE_FACTOR: 2.5
    NEG_SAMPLING_RATIO: 7
    SLOW_FAST_RATIO: 0.8
    PREC: "amp"