DTD_TEMPLATES = {
    "gauzy": [
        "Gauzy material is thin and sheer.",
        "Gauzy material looks like thin, sheer fabric.",
        "Gauzy material is usually thin and lightweight.",
        "Gauzy material is thin, light fabric with a loose weave.",
        "Gauzy material is usually light and airy, with a loose weave.",
        "Gauzy material is typically thin, see-through, and may have a slightly fuzzy or textured surface.",
        "Gauzy material is thin and transparent.",
        "Gauzy material is thin and often transparent.",
        "Gauzy material is often thin, light, and delicate-looking.",
        "Gauzy material is extremely thin and typically transparent.",
        "The surface of a gauzy object is covered in thin, translucent fabric.",
        "A gauzy surface is covered in thin, transparent fabric.",
        "Gauzy surfaces are usually thin and transparent.",
        "A \"gauzy\" surface looks like a thin layer of material that is spread over something.",
        "A gauzy surface is covered with a thin layer of material, such as gauze.",
        "A gauzy surface is covered with a thin layer of fabric, often sheer or transparent.",
        "A \"gauzy\" surface is typically thin and sheer, often with a delicate or transparent appearance.",
        "A \"gauzy\" surface is one that is thin and transparent, like a thin piece of fabric.",
        "A \"gauzy\" surface is a surface that is covered with a thin layer of material.",
        "A \"gauzy\" surface usually has a lot of small holes in it, so that it looks a bit like a net."
    ],
    "meshed": [
        "Meshed material is material that has been cut into a mesh or netting.",
        "Meshed materials are those that have been combined or interwoven with each other.",
        "Mesh is a type of fabric that has a wide open space between the threads.",
        "\"Meshed\" material typically looks like a screen or net.",
        "Meshed material has a rough, uneven surface with small holes throughout.",
        "Meshed material is a type of fabric made from interlocking loops of thread.",
        "Meshed fabric is usually made of a mesh-like material, with small holes throughout.",
        " Meshed material is a type of fabric that has small holes or gaps in it.",
        "Meshed material is a type of fabric that has small holes or openings throughout its surface.",
        "The mesh material looks like a net or a screen.",
        "A meshed surface is made up of a series of small triangles.",
        "A meshed surface looks like a 3D net or wireframe.",
        "A meshed surface is a three-dimensional surface composed of a network of interconnected triangles.",
        "A meshed surface is a three-dimensional surface that is made up of a network of interconnected triangles.",
        "A meshed surface is a surface that has been divided into a regular grid of small polygons.",
        "A meshed surface is a smooth surface with a network of small holes or pores.",
        "A meshed surface looks like a mesh or net.",
        "A meshed surface looks like a three-dimensional grid.",
        "A meshed surface looks like a surface that has been divided into a grid.",
        "A \"meshed\" surface has a grid-like appearance."
    ],
    "cracked": [
        "Cracked material may have fine lines running through it or large chunks missing.",
        "A cracked material looks like it has been damaged or split open.",
        "Cracked materials can have a wide variety of appearances, but all feature some sort of line or fissure running through them.",
        "Cracked material is usually dry and has a rough surface.",
        "Cracked material may have sharp edges.",
        "A cracked material may have a web-like or spiderweb-like appearance.",
        "Cracked materials may have jagged or smooth edges.",
        "Cracked material typically looks like a spider web or a line running through it.",
        "Cracked material may appear broken, fractured, or split.",
        "Cracked material looks like it has been split or broken into multiple pieces.",
        "A cracked surface may have a large or small crack running through it.",
        "A cracked surface can look like a spiderweb, with a series of cracks radiating out from a central point.",
        "A broken surface has an irregular, jagged shape.",
        "A \"cracked\" surface usually has small cracks running through it.",
        "A cracked surface has a jagged, broken appearance.",
        "A \"cracked\" surface is typically dry, hard, and/or brittle.",
        "A cracked surface is one that has small fissures or breaks in it.",
        "A cracked surface usually looks like a regular surface that has been broken or damaged in some way.",
        "A cracked surface has multiple fissures or cracks running through it.",
        "A cracked surface can have a variety of different appearances."
    ],
    "stratified": [
        "Stratified material is a material that is layered or banded.",
        "Strata are layers of sedimentary rock that have been formed by deposits of material that have been laid down in layers.",
        "\"Stratified\" material generally has a layered appearance, with different materials of differing densities and/or sizes appearing in distinct layers.",
        "Stratified materials generally have a layered appearance, with each layer having a different composition.",
        "Stone that has been split into thin, parallel layers.",
        "Strata are layers of sedimentary rock that have been laid down over time.",
        "A layer of material that consists of different types of materials is called stratified.",
        "A stratified material is a material that is layered.",
        "A stratified material is a material that has been layered.",
        "Strata (layers) of sedimentary rock are usually visible in cliffs, road cuts, and quarry walls.",
        "A stratified surface is a surface that has been divided into layers.",
        "A stratified surface has a layered appearance, with different layers of material that have different properties.",
        "A stratified surface consists of different layers that have been deposited over time.",
        "A stratified surface is a surface that has been divided into a series of layers.",
        "A stratified surface is one that has been divided into layers.",
        "A stratified surface is one that is made up of a series of layers.",
        "A stratified surface looks like a layer cake, with each layer being a different material.",
        "A stratified surface has layers of different materials that are arranged in a specific order.",
        "A stratified surface is a flat surface that is divided into layers, with each layer having a different color or composition.",
        "A stratified surface looks like a series of horizontal layers that have been stacked on top of each other."
    ],
    "scaly": [
        "\"Scaly\" material has a rough, dry surface with large flakes or scales.",
        "\"Scaly\" material typically has a rough, dry texture and may be covered in small scales.",
        "A scaly material would look like a material that has been cut up into small scales, or thin, flat pieces.",
        "Scaly material has a rough, dry texture and can flake off in scales.",
        "A scaly material typically has a rough, dry surface with small scales that can flake off easily.",
        "A scaly material is one that is covered in small, thin scales.",
        "Some scaly materials can appear to be dry and flaky, while others may look more wet and slimy.",
        "A scaly material has a dry, flaky surface.",
        "The word \"scaly\" is used to describe a number of different things, but most commonly it is used to describe skin that is dry, flaky, and peeling.",
        "A scaly material usually has a rough, dry texture with small scales that can be flaked or peeled off.",
        "A scaly surface is an area of skin that is covered in scales.",
        "A scaly surface looks dry, rough, and flaky.",
        "A scaly surface is usually covered in small, thin scales.",
        "Scaly surfaces are usually dry, flaky, and/or rough.",
        "A scaly surface is a surface that is covered in small, thin scales.",
        "A scaly surface looks dry, rough, and flaky.",
        "A scaly surface is covered with small, hard pieces that look like scales.",
        "A scaly surface typically looks dry, rough, and crusted.",
        "A scaly surface is usually dry and flaky, and may be covered in scales.",
        "A scaly surface has a dry, flaky texture."
    ],
    "swirly": [
        "\"Swirly\" material is usually Shiny and Reflective.",
        "Swirly materials are materials that have a lot of movement and are very flowy.",
        "This is tough to describe without a picture, but \"swirly\" material typically has a lot of movement and texture.",
        "The term \"swirly\" is often used to describe materials that are spiral in shape or that have a spiral design.",
        "The appearance of swirly material varies depending on the specific material in question.",
        "The word \"swirly\" is often used to describe something that is spiral in shape, or that has a lot of curves and swirls.",
        "\"Swirly\" material is usually made up of two or more colors that are swirled together to create a unique pattern.",
        "The word \"swirly\" is often used to describe materials with a lot of texture or patterns.",
        "Swirly material usually has a lot of movement and is very fluid.",
        "Swirly material is material with a lot of small, intricate patterns.",
        "A \"swirly\" surface usually looks like a spiral or a series of loops.",
        "A \"swirly\" surface usually has a lot of small, tight curves.",
        "A swirly surface is curved and has a lot of movement.",
        "A swirly surface is a surface that has a lot of curves and swirls.",
        "A swirly surface is one that is not smooth, but instead has a lot of curves and swirls.",
        "A swirly surface looks like a surface that has been spiralized.",
        "The surface of a swirly object is twisted or spiraled.",
        "A swirly surface typically has a lot of texture and looks like it has been whirled around.",
        "A \"swirly\" surface may have a spiral or helical shape, or it may simply be curved or undulating.",
        "A swirl surface typically looks like a spiral or helix pattern."
    ],
    "perforated": [
        "A perforated material has small holes punched throughout its surface.",
        "A perforated material has small holes punched through it.",
        "\"Perforated\" material is a type of fabric that has small holes or slay-like designs cut into it.",
        "\"Perforated\" material is a type of material that has small holes in it.",
        "Perforated material is a material that has been punctured with small holes.",
        "A perforated material has small holes throughout its surface.",
        "\"Perforated\" material is a type of material that has small holes in it.",
        "\"Perforated\" material has small holes throughout its surface.",
        "Perforated paper has tiny holes punched through it.",
        " Perforated material has small holes spread evenly throughout the material.",
        "A perforated surface has small holes in it.",
        "A \"perforated\" surface has small holes all over it.",
        "A \"perforated\" surface has a lot of small holes in it.",
        "A perforated surface is a surface with tiny holes in it.",
        "A perforated surface has small holes in it.",
        "A perforated surface has small holes in it.",
        "A perforated surface has small holes in it.",
        "A perforated surface looks like a surface that has been punctured or pierced with small holes.",
        "A perforated surface looks like it has small holes punched through it.",
        "A perforated surface is one that is covered in small holes."
    ],
    "pleated": [
        "Pleated material is material that has been folded into a series of parallel creases.",
        "A pleat is a type of fold in fabric that is created by folding the fabric twice in the same direction to create a section of fabric that is three times the original width.",
        "Pleated material has a series of folds or wrinkles in it.",
        "Pleated fabric is fabric that has been folded or gathered into pleats.",
        "Pleated material has a series of folded creases that give the fabric a textured look.",
        "Pleated material is fabric that has been folded over and sewn in a series of accordion-like folds.",
        "#Pleated fabric has a series of folds or creases that run parallel to each other.",
        "Pleated material typically has a series of folding lines that give the material a more textured look.",
        "Pleated material is material that has been gathered or folded into pleats.",
        "Pleated material is folded material that has a lot of folds in it, similar to the pleats on a skirt.",
        "Image result for pleated surface.",
        "A pleated surface has a series of ridges and valleys that resemble the folds of a pleated skirt or pair of pants.",
        "A pleated surface is one that has folds or creases in it, like a pleated skirt.",
        "A pleated surface looks like a series of folds or wrinkles.",
        "A pleated surface has small, regular folds, like the pleats on a skirt.",
        "A pleated surface looks like it has folds or wrinkles in it.",
        "A pleated surface is one that has been folded or creased so that it contains a series of parallel folds.",
        "A pleated surface is one that has folds or creases in it.",
        "A pleated surface is one that has been formed by folding or pressing fabric so that it forms a series of parallel folds.",
        "A \"pleated\" surface is one that has been folded or creased into a series of parallel ridges and valleys."
    ],
    "flecked": [
        "A flecked material has small pieces of a different color or material interspersed throughout it.",
        "A flecked fabric has a mottled or speckled appearance.",
        "Flecked material has small pieces of a different color or material woven into it.",
        "The definition of flecked is having small patches of color.",
        "flecked material typically has small pieces of a different color or material mixed in with the main color or material.",
        "A material with flecks is usually speckled with small pieces of a different color.",
        "\"Flecked\" material is covered with small pieces or streaks of a different color.",
        "Flecks of material are small pieces or streaks of something.",
        "Flecked material contains small flecks or pieces of another material mixed in with it.",
        "A flecked material has small, irregular pieces of a different color throughout it.",
        "A flecked surface is usually made up of small pieces or flecks of a material.",
        "A flecked surface has small pieces of another material mixed in with it.",
        "A flecked surface has small spots or specks of color.",
        "A flecked surface is covered in small pieces or streaks of a different color.",
        "A flecked surface is one that has small specks or flecks of another color or material on it.",
        "A flecked surface looks like it has small pieces of something else on its surface.",
        "A flecked surface is one that has been deliberately covered with small spots or specks of a different color or material.",
        "There is no definitive answer to this question since it can depend on the material in question and the size of the flecks.",
        "A \"flecked\" surface has small, irregular pieces of another material mixed in with it.",
        "A flecked surface usually has a light and a dark color, and the colors are usually in a small pattern."
    ],
    "fibrous": [
        "Fibrous material looks like a bundle of thin, flexible fibers.",
        " Material that is fibrous is usually composed of long, thin fibers.",
        "Fibrous material is usually stringy and has a \"hairy\" appearance.",
        "Fibrous material is often stringy, and can be made into yarn or fabric.",
        "Fibrous material often looks like string or yarn.",
        "Fibrous material is stringy and looks like a bundle of fibers.",
        "Fibrous material can look like string, wool, or paper.",
        "Fibrous material typically looks like a bundle of thin, thread-like fibers.",
        "Fibrous material looks like a string or a thread.",
        "A fibrous material looks like a bunch of fibers woven together.",
        "A fibrous surface looks like a surface that is covered in tiny fibers.",
        "A fibrous surface can look like a piece of burlap or tweed fabric.",
        "A \"fibrous\" surface is one that is made up of small, thin fibers.",
        "A fibrous surface is one that is covered in small, thread-like fibers.",
        "A fibrous surface looks like a surface that is covered in fine, hair-like fibers.",
        "A fibrous surface is a surface that is covered in small fibers.",
        "A \"fibrous\" surface is one that is covered in small, thin fibers.",
        "A fibrous surface usually has a rough, scaly appearance.",
        "A fibrous surface is covered in tiny fibers.",
        "A fibrous surface is a surface that is covered in small fibers."
    ],
    "polka-dotted": [
        "Almost any fabric can be polka-dotted, but the polka dots are usually a different color than the background fabric.",
        "Polka-dotted material is covered in small, round dots.",
        "A polka-dotted material hassmall, round spots that are evenly spaced.",
        "Polka-dotted material is covered in small, round dots.",
        "Polka-dotted material typically has small, round white dots on a colored background.",
        "Polka-dotted material typically has little dots all over it.",
        "Polka-dotted material generally has a white or light-colored background with small, evenly-spaced black or dark-colored dots.",
        "Polka-dotted material features small, evenly-spaced dots on a solid background.",
        "A polka-dotted material has white dots on a colored background.",
        "The polka dot is a pattern consisting of an array of circles of the same size.",
        "A polka-dotted surface is one that is covered with small, round spots.",
        "A polka-dotted surface looks like it has small, round spots on it.",
        "A polka-dotted surface is spotted or flecked with a small, round shape.",
        "A polka-dotted surface has round spots that are usually the same color as the background.",
        "A polka-dotted surface is a surface with small, round spots.",
        "A polka-dotted surface is one that is covered with small, round spots.",
        "A polka-dotted surface is covered in small, round spots.",
        "A surface with polka dots on it would look like a surface with lots of small, round dots on it.",
        "A polka-dotted surface has small, round spots that are evenly spaced.",
        "A polka-dotted surface is a surface with small, round dots that are evenly spaced."
    ],
    "chequered": [
        "A chequered material has a pattern of light and dark squares.",
        "Chequered material often has a pattern of light and dark squares.",
        "Chequered material typically has a pattern of light and dark squares.",
        "Chequered material typically has a pattern of light and dark squares.",
        "Chequered material typically has a pattern of alternating light and dark squares, similar to a checkerboard.",
        "A \"chequered\" material typically has a pattern of alternating light and dark squares, similar to a checkerboard.",
        "Chequered fabric has a pattern of small, repeated squares in two colors.",
        "Chequered material has a pattern of small squares, usually in two colors.",
        "\"Chequered\" material typically has a pattern of alternating light and dark squares, similar to a checkerboard.",
        "A chequered material is typically a fabric with a pattern of small, regular checks or squares.",
        "A chequered surface is typically a surface that is covered in a checkerboard pattern.",
        "A chequered surface consists of a series of small, regularly-spaced raised squares.",
        "A chequered surface is one that is covered with a regular pattern of squares or crossed lines.",
        "A \"chequered\" surface has a checkerboard pattern.",
        "A chequered surface has a pattern of small squares.",
        "The surface of a chequered object is covered in a pattern of small squares.",
        "A chequered surface has a pattern of light and dark squares.",
        "A chequered surface has a regular pattern of squares, typically black and white.",
        "A chequered surface is a surface that has a pattern of squares or rectangles on it.",
        "A chequered surface has a regular pattern of squares or rectangles, usually in two different colors."
    ],
    "blotchy": [
        "A blotchy material has an uneven surface with patches of different colors or shades.",
        "A blotchy material has patches of different colors or shades.",
        " Blotchy material typically has an uneven pattern or dark and light areas.",
        "A blotchy material is one that has dark and light areas, usually in an irregular pattern.",
        "\"Blotchy\" material typically has an irregular or uneven pattern.",
        "\"Blotchy\" material is usually characterized by an uneven color or texture.",
        "\"Blotchy\" material is usually a light-colored fabric that has dark spots on it.",
        "A blotchy material has an uneven distribution of color or shading.",
        "Blotchy material can look like it has water spots, or like it has been stained with a substance that has not been evenly distributed.",
        "The word \"blotchy\" is often used to describe skin that has an uneven color.",
        "A \"blotchy\" surface looks like a surface with blotches of color on it.",
        "A blotchy surface looks like it has small, dark spots all over it.",
        "A blotchy surface is one that is not smooth, but instead has patches of color or texture.",
        "A blotchy surface is one that has lots of different colors on it, usually without any pattern.",
        "A \"blotchy\" surface looks like it has large, uneven spots of color.",
        "A blotchy surface usually refers to a surface that is not even or smooth, but instead has patches of different colors or shades.",
        "A \"blotchy\" surface is one that is not smooth, but has bumps or ridges.",
        "A \"blotchy\" surface has an uneven texture, with visible marks or discoloration.",
        "A blotchy surface can refer to a number of different things, but generally it is an uneven surface with patches of discoloration.",
        "A blotchy surface looks like a surface with irregular patches of color."
    ],
    "stained": [
        "There is no definitive answer to this question since the term \"stained\" is relative.",
        "The term \"stained\" is often used to describe items that are discolored or have marks on them.",
        "Stained material is material that is discolored by a substance.",
        "A material that is stained will have a discoloration on its surface.",
        "A stained material is one that has been discolored by a substance.",
        "Stained material is discolored or spotted.",
        "Stained material is typically yellow, brown, or black in color.",
        "\"Stained\" material is any fabric that has had a liquid spilled on it.",
        "Stained materials are usually darker than the surrounding material, although the exact color can vary.",
        "Stained materials are usually darker in color than the surrounding material, although the stain may be lighter or darker than the original color of the material.",
        "A nailed or stapled surface that has been painted over without proper preparation will result in the paint failing prematurely.",
        "A stained surface looks like it has been discolored by a substance.",
        "A stained surface looks like it has been damaged by a substance.",
        "A \"stained\" surface is a discolored or uneven surface.",
        "A \"stained\" surface is a surface that has been discolored by a substance.",
        "A \"stained\" surface is one that has been marked or discolored by a substance.",
        "A stained surface is usually discolored or has a mark on it.",
        "A \"stained\" surface is one that has been contaminated with a liquid or other substance.",
        "A \"stained\" surface is one that has had a liquid spilled on it, which has then dried, leaving a mark.",
        "A \"stained\" surface looks like it has been discolored by a substance."
    ],
    "crystalline": [
        "A crystalline material looks like a geometric pattern of repeating shapes.",
        "A crystalline material is typically transparent and has a highly regular, repeating internal structure.",
        "A crystalline material has a repeating, symmetrical pattern.",
        "Crystalline material is typically transparent or translucent, with a uniform structure.",
        "Under a microscope, crystalline material looks like a series of interconnected, repeating geometric shapes.",
        "Crystalline materials have a repeating, three-dimensional structure.",
        "Crystalline material typically looks like a regular crystal.",
        "A crystalline material is one that is made up of a repeating, three-dimensional pattern of atoms, molecules, or ions.",
        "The term \"crystalline\" refers to the orderly arrangement of atoms in a material.",
        "A crystalline material looks like a diamond or a crystal.",
        "A crystalline surface is a smooth, flat surface that is atomically level and has a regular or repeating pattern.",
        "A \"crystalline\" surface has a repeating, 3-dimensional structure.",
        "A \"crystalline\" surface looks like a Shattered Glass surface.",
        "A crystalline surface looks smooth and shiny, like a piece of glass.",
        "A crystalline surface has a repeating, three-dimensional pattern.",
        "A crystalline surface is smooth and free of pits or other imperfections.",
        "A crystalline surface is smooth and shiny, like a mirror.",
        "A crystalline surface is one that is made up of small, repeating units called crystals.",
        "A crystalline surface is one that is smooth, hard, and polished.",
        "A crystalline surface is one that is smooth and made up of small, regular crystals."
    ],
    "porous": [
        "Porous material is a material that has tiny holes in it.",
        "A porous material has small holes or pores that allow liquid or gas to pass through.",
        "Porous material is material that has small holes throughout it.",
        "Porous materials have small holes throughout them.",
        "Porous materials have small holes throughout them.",
        "Porous material is typically full of tiny holes.",
        "Porous materials are full of tiny holes.",
        "\"Porous\" materials have tiny holes in them that allow fluids and gases to pass through them.",
        "Porous material has tiny holes all over its surface.",
        "A porous material has tiny holes throughout it.",
        "A \"porous\" surface looks like a surface that has a lot of tiny holes in it.",
        "A porous surface has tiny holes in it.",
        "A porous surface is one that has tiny holes or pores.",
        "A porous surface has tiny holes that allow liquids or gases to pass through.",
        "a surface with small pores or holes.",
        "A porous surface is covered in tiny holes.",
        "A \"porous\" surface has tiny pores or holes that liquids or gases can pass through.",
        "A porous surface is a surface that has tiny holes in it.",
        "A porous surface is one that is full of tiny holes.",
        "A porous surface is one that has small holes or pores."
    ],
    "banded": [
        "Banded material is material that has been wrapped around something else, typically in a strip or bands.",
        "Banded material is two pieces of material that are joined together by a strip of material in the middle.",
        "Banded material usually has stripes or other patterns running across it.",
        "Banded material looks like it has stripes running through it.",
        "Banded material has a series of stripes or other markings that run around it.",
        "\"Banded\" material is material that has been wrapped in a band or similar object.",
        "A banded material typically has stripes or bands of color.",
        "\"Banded\" material typically has a stripe or series of stripes running perpendicular to the grain.",
        "Banded material has a stripe or series of stripes running through it.",
        "Banded material is a type of fabric that has been dyed or printed with stripes or other patterns that are of different colors.",
        "A banded surface looks like it has stripes or bands running across it.",
        "A banded surface has alternating light and dark stripes.",
        "A banded surface is one that consists of a series of parallel lines or bands.",
        "A banded surface is a surface that contain bands, or stripes, of color.",
        "A banded surface has alternating light and dark stripes.",
        "A banded surface is a surface that has visible bands or stripes.",
        "Banding is a type of surface defect that appears as a series of dark and light stripes on the surface of the material.",
        "A banded surface is made up of different layers of materials that are of different colors.",
        "A banded surface is made up of bands or layers of different colors, materials, or textures.",
        "A banded surface is a surface that is made up of a series of bands, or stripes."
    ],
    "lacelike": [
        "\"Lacelike\" material is usually made of a very fine, delicate fabric.",
        "Lacelike material is usually thin and delicate, with a lot of small holes or gaps.",
        "Lace is a delicate fabric with an open, intricate weblike design.",
        "Lacelike material typically has a hole pattern that resembles that of a doily.",
        "Lacelike material is typically very delicate and has a lot of small holes in it.",
        "Lace is a light, smooth fabric with a hole pattern.",
        "The word \"lacelike\" is typically used to describe something that is delicate, intricate, and beautiful.",
        "Lacelike material looks like a piece of lace.",
        "Lacelike material is usually thin and delicate, with a lot of small holes or openings.",
        "A lacelike material looks like a piece of lace.",
        "A \"lacelike\" surface has a lot of small holes in it.",
        "A lacelike surface is usually thin and delicate, with a lot of small holes or openings.",
        "A lacelike surface is one that is covered in a pattern of small holes, like a piece of lace.",
        "A lacelike surface is a surface with a lot of tiny holes in it, like a piece of lace.",
        "Lacelike surfaces are covered in small holes or indentations, like a piece of lace.",
        "A lacelike surface is one that is covered in a pattern of small holes, like a piece of lace.",
        "Lace is a delicate fabric made of interwoven threads, typically of cotton, nylon, or polyester.",
        "A lacelike surface is a surface that has a lot of small holes in it, like a piece of lace.",
        "A lacelike surface has a lot of small holes in it that make it look like lace.",
        "A lacelike surface has a delicate, intricate, and open structure."
    ],
    "sprinkled": [
        "Sprinkled material is material that has been sprinkled on something.",
        " Sprinkled materials are usually in the form of a powder.",
        "Sprinkled material typically looks like small pieces or grains of something scattered around.",
        "This depends on the material being sprinkled.",
        "A sprinkling of materials looks like a light dusting or covering.",
        "\"Sprinkled\" material is usually small pieces or flakes of a substance.",
        "\"Sprinkled\" material is typically small pieces or granules of a substance.",
        "A material that has been sprinkled looks like it has been covered with a light dusting of something.",
        "Sprinkled material looks like small pieces or droplets of something that has been scattered or spread over an area.",
        "The word \"sprinkled\" can mean to scatter something lightly over a surface, so the material would be scattered lightly and would not be in any one particular place.",
        "A sprinkled surface is one that is covered with a light layer of a substance, such as water droplets, snow, or sugar.",
        "A \"sprinkled\" surface is a surface that is covered in a light layer of something, typically a powder.",
        "A surface that has been \"sprinkled\" will appear to have small droplets of water on it.",
        "A \"sprinkled\" surface is covered in small droplets of water.",
        "A \"sprinkled\" surface is covered in small droplets of water.",
        "A sprinkled surface is evenly covered with small drops of liquid.",
        "There is no definitive answer to this question, as the term \"sprinkled\" can mean different things to different people.",
        "A sprinkled surface indicates an irregular distribution of small drops or particles.",
        "A sprinkled surface is one that has been covered with a light layer of something, like sugar or salt.",
        "A sprinkler is a device used to apply water to an area in a controlled manner."
    ],
    "bubbly": [
        "A \"bubbly\" material looks like a material that has a lot of small bubbles in it.",
        "Bubbly material often looks like foamy bubbles.",
        "\"Bubbly\" material looks like a liquid with a lot of small bubbles in it.",
        "A material that is bubbly would have a lot of small air pockets or gaps throughout.",
        "A bubbly material is one that has a lot of small holes orWh bubbles in it.",
        "A \"bubbly\" material typically has a lot of small bubbles throughout it.",
        "Bubbly material looks foamy and full of bubbles.",
        "A bubbly material often looks like a foam.",
        "When materials are bubbly they appear to have small bubbles caught within them.",
        "Bubbly material is typically light and frothy in appearance.",
        "A bubbly surface looks like a surface that is covered in bubbles.",
        "A \"bubbly\" surface is one that is covered in a lot of small bubbles.",
        "A bubbly surface looks like a surface with a lot of small bubbles on it.",
        "A surface that is \"bubbly\" typically has a lot of small holes or bumps on it.",
        "The surface of a liquid that is \"bubbly\" is covered in tiny bubbles.",
        "A bubbly surface is a surface that has a lot of small bubbles on it.",
        "A \"bubbly\" surface looks like a surface with a lot of bubbles on it.",
        "A \"bubbly\" surface has small, round protrusions.",
        "A \"bubbly\" surface is one that is covered with small, round bubbles.",
        "A \"bubbly\" surface is covered in small, round bumps."
    ],
    "lined": [
        "Lined material has a second layer of fabric sewn beneath the outer layer.",
        "Linen is a textile made from the fibers of the flax plant.",
        "Lined material is fabric that has been sewn to another fabric along the edges.",
        "Lined materials have a second layer of fabric sewn on the inside of the garment.",
        "Lined material is one that has a second layer of fabric sewn on the inside.",
        "A lined material is a fabric that has a secondary fabric sewn to the back of it.",
        "Lined material is fabric that has a second layer of fabric sewn on top of it.",
        "\"Lined\" material has a second layer of fabric sewn inside the garment.",
        "Lined material has a second layer of fabric sewn on top of the main fabric.",
        "A lined material is a type of fabric that has a second layer of fabric underneath the outer layer.",
        "A \"lined\" surface is a surface that has been divided into a series of parallel lines.",
        "A lined surface is a surface with a line on it.",
        "A lined surface is a flat surface with lines drawn on it.",
        "A lined surface has a consistent texture throughout.",
        "A lined surface has parallel lines running along it.",
        "A lined surface has straight lines running across it.",
        "A lined surface looks like a surface with parallel lines running across it.",
        "A lined surface has a consistent texture throughout with no variation.",
        "A lined surface is a surface with a consistent texture or pattern.",
        "A lined surface has a definite boundary, beyond which there is nothing."
    ],
    "veined": [
        "Usually, \"veined\" material has lines or streaks running through it.",
        "Veined material has a network ofthin lines or streaks running through it.",
        "A \"veined\" material has lines or streaks running through it.",
        "Veined material is material that has visible lines or streaks running through it.",
        "Veined materials have lines or streaks running through them.",
        "This type of material has a pattern that looks like veins running through it.",
        "The word \"veined\" can describe a material that has lines or streaks running through it, or a material that is marbled with different colors.",
        "Typically, \"veined\" materials contain lines or streaks of a different color or material running through them.",
        "Veined material is material that has veins or lines running through it.",
        "Veined materials have lines or streaks running through them.",
        "Veined surfaces contain lines or streaks that resemble veins in a leaf.",
        "A veined surface is covered in thick, raised lines that resemble veins in a human body.",
        "A veined surface has raised lines that look like veins in a leaf.",
        "A surface with veins is one that has lines or markings that look like veins in a leaf.",
        "A veined surface is a surface that has lines or streaks running through it.",
        "A \"veined\" surface has thin lines or grooves running through it.",
        "A \"veined\" surface is one that has lines or streaks running through it.",
        "A veined surface has lines or streaks running through it.",
        "A \"veined\" surface is one that is marked by a network of fine lines or cracks.",
        "A veined surface is a surface with a pattern of lines or streaks that resemble veins."
    ],
    "bumpy": [
        "Reference material for \"bumpy\" material: https://www.",
        "\"Bumpy\" material typically has a textured surface with small bumps or ridges.",
        "Bumpy material has a lot of small raised bumps on the surface.",
        "Bumpy material has an uneven surface, with raised and lowered areas.",
        "Bumpy material generally looks like it has bumps on it.",
        "Bumpy material has an uneven surface, with protrusions and indentations.",
        "Bumpy material typically has an irregular surface with raised areas.",
        "A \"bumpy\" material has a textured surface with many small protrusions.",
        "The word \"bumpy\" is used to describe a texture that is not smooth.",
        "\"Bumpy\" material is material that is not smooth.",
        "A \"bumpy\" surface is not smooth.",
        "A \"bumpy\" surface is a surface that has many small protrusions or indentations.",
        "A \"bumpy\" surface looks like a surface with bumps on it.",
        "A \"bumpy\" surface is one that has a lot of small hills and valleys.",
        "A \"bumpy\" surface contains many small bumps.",
        "A bumpy surface looks like it has a lot of bumps on it.",
        "A \"bumpy\" surface usually has small raised bumps on it.",
        "A bumpy surface has a lot of bumps on it.",
        "A \"bumpy\" surface can have many different looks, but generally it is a surface with a lot of raised areas or protrusions.",
        "A \"bumpy\" surface has protrusions or indentations that make it uneven."
    ],
    "paisley": [
        "Paisley material is typically a printed cotton fabric with a patterns of curved shapes.",
        "Paisley material consists of curved shapes with swirling lines, similar to the design on a paisley tie.",
        "Paisley is a design that is created by a series of curved shapes that are arranged in a repetitive pattern.",
        "Paisley is a design that is made up of curved shapes that resemble teardrops or comma shapes.",
        "Paisley material typically features a repeating pattern of curved shapes.",
        "Paisley material is a textile print with a patterns of curved shapes resembling teardrops.",
        "Paisley is a printed fabric with a pattern of curved shapes that look like leaves.",
        "Paisley is a droplet-shaped vegetal motif, similar to half of a tear, often used in fabrics, wallpaper, and other patterned designs.",
        "Paisley fabric typically has a colorful, intricate design.",
        "Paisley is a decorative fabric design made of intricate curved shapes.",
        "A paisley surface is characterized by a repeating pattern of curved shapes that resemble teardrops or comma shapes.",
        "Paisley surfaces have a swirly, organic pattern.",
        "The paisley surface is characterized by a series of curved lines that intersect in a teardrop-shaped motif.",
        "A paisley surface is a surface with a repeating pattern of abstract shapes.",
        "Paisley surfaces are usually covered in a repeating pattern of curved shapes.",
        "A paisley surface is typically characterized by a curved, teardrop-shaped motif.",
        "A paisley surface is usually curved or wavy, with a pattern of repetitive shapes that resemble teardrops or leaves.",
        "A paisley surface is usually decorated with a repeating pattern of curved, comma-shaped figures.",
        "A paisley surface is typically composed of a series of curved shapes that resemble the teardrop-shaped vegetative motif of the same name.",
        "A \"paisley\" surface looks like an intricate, curved design that is often used in fabrics and wallpapers."
    ],
    "potholed": [
        "Potholed material typically looks like a broken or crumbled up pavement.",
        "Potholed material generally looks like abroken-up road.",
        "The samples are from a light-colored potholed material.",
        "Potholed material typically looks like gravel or dirt.",
        "Potholed material is typically cracked and full of holes.",
        "\"Potholed\" material is typically a type of pavement that has been damaged by weather or traffic.",
        "Potholing is a method of underground mining in which narrow shafts are dug outward from an existing opening.",
        "Potholed material is full of holes.",
        "\"Potholed\" material typically looks like a dry, cracked, and/or crumbled road surface.",
        "Potholed material is typically a gray or dark gray color.",
        "A road that is \"potholed\" is full of holes, or potholes.",
        "A potholed surface is full of holes.",
        "A potholed surface is one that is full of small holes, usually caused by the wearing away of the material.",
        "A \"potholed\" surface looks like a piece of pavement or asphalt that has been damage by a hole.",
        "A \"potholed\" surface is cracked and bumpy.",
        "A road that is potholed has large holes in it.",
        "A potholed surface is one that is full of small holes, often causing it to be bumpy.",
        "A potholed surface looks like a surface that has been filled with holes.",
        " Well-used roads often develop potholes.",
        "A potholed surface is usually full of small holes or pits."
    ],
    "waffled": [
        "Waffled material often looks like honeycomb or a grid.",
        "A waffled material is a fabric that has a raised, honeycomb-like texture.",
        "\"Waffled\" material may have a raised, grid-like texture.",
        "Waffled material typically has a textured or honeycomb-like appearance.",
        "Waffled material can have a textured or embossed look.",
        "\"Waffled\" material looks like a series of small, raised squares.",
        "\"Waffled\" material is material that is made up of a series of small, raised ridges.",
        "Waffled material has a raised, grid-like pattern.",
        "\"Waffled\" material looks like a series of raised squares.",
        "Waffled fabric has a textured, honeycomb-like appearance.",
        "A waffled surface looks like the surface of a waffle.",
        "A \"waffled\" surface is a surface with a series of raised bumps.",
        "A \"waffled\" surface is one that has been covered with a series of indentations, making it look like a waffle.",
        "A \"waffled\" surface has a series of small, raised squares.",
        "A waffled surface is a declined surface that is covered in small, raised squares.",
        "A waffled surface is one that is covered in a grid or diamond pattern.",
        "A \"waffled\" surface looks like a surface with a lot of ridges or peaks and valleys.",
        "A waffled surface has a texture that is similar to that of a waffle.",
        "A waffled surface is one that has a lot of small indentations, making it look like a waffle.",
        "A \"waffled\" surface has a series of indentations that resemble a waffle."
    ],
    "pitted": [
        "Pitted material has small indentations or holes on the surface.",
        "A pitted material has small indentations on its surface.",
        "Pitted material has small indentations or holes on the surface.",
        "A pitted material has small indentations or holes on its surface.",
        "A pitted surface has small craters or depressions.",
        "Pitted material has small depressions or holes on its surface.",
        "\"Pitted\" material is material that has been worn away, typically by being rubbed or scratched repeatedly.",
        "A pitted material has small indentations or holes on its surface.",
        "Pitted material has small holes or indentations on the surface.",
        "Pitted material looks like small holes or indentations on a surface.",
        "A pitted surface is one that has small depressions or holes in it.",
        "When a surface is \"pitted,\" it means there are small depressions or holes in the surface.",
        " imagenotavailable.",
        "A pitted surface looks like it has small craters.",
        "A pitted surface has small craters or indentations.",
        "A pitted surface is a surface that has been damaged by small crater-like depressions.",
        "A pitted surface has small craters or indentations.",
        "A pitted surface has small holes or indentations.",
        "A pitted surface looks like it has tiny craters or divots.",
        "A pitted surface is one that has small craters or indentations."
    ],
    "frilly": [
        "The definition of frilly is something that is fancily decorated or lacy.",
        "The best way to describe frilly fabric is to say that it is fabric with a lot of ruffles.",
        "Frilly material looks like ruffles or lace.",
        "A frilly material is usually a light-weight fabric with a lot of texture.",
        "\"Frilly\" material can be many different things, but usually it refers to material that is very delicate looking, and often has a lot of small details.",
        "A frilly material is usually a type of fabric that is intricately designed with a lot of ruffles or lace.",
        "Frilly material is usually lightweight and has a lot of texture.",
        "A frilly material might have a lot of ruffles or a lacy pattern.",
        "Frilly material is material that has a lot of small, delicate folds in it.",
        "This is a difficult question because \"frilly\" can mean different things to different people.",
        "A frilly surface can be described as having a lot of small, raised bumps or protrusions.",
        "A frilly surface is one that has a lot of ruffles or other decorations.",
        "A \"frilly\" surface is a surface with a lot of small, delicate details.",
        "A \"frilly\" surface is one that is covered in a lot of small, decorative details.",
        "A \"frilly\" surface looks like it is covered in small, loops or ruffles.",
        "A frilly surface looks like it has a lot of small bumps or ridges.",
        "A frilly surface is one with a lot of small, decorative details.",
        "A frilly surface is one that has a lot of small, decorative details.",
        "A \"frilly\" surface is one that is covered with a lot of small, decorative details.",
        "A \"frilly\" surface is one that is decorated with a lot of small, decorative details."
    ],
    "spiralled": [
        "\"Spiraled\" material looks like a spiral or a coil.",
        " spiraled material looks like a corkscrew.",
        "It looks like a helix or a spiral.",
        "Spiralled material looks like it has been wound around something in a spiral shape.",
        "A spiralled material is a material that has been cut or shredded into long, thin strips that resemble a spiral.",
        "\"Spiralled\" material is material that is coiled or twisted in a spiral shape.",
        "Spiraled material is generally cylindrical in shape, with a spiral pattern running along its length.",
        "When looking at a \"spiralled\" material, it would appear to be winding its way around in a circular pattern.",
        "\"Spiralled\" material is usually twisted or coiled.",
        "Spiralled material is material that is coiled or twisted together in a spiral shape.",
        "A spiralled surface looks like a surface that has been wrapped around a spiral.",
        "A spiralled surface is a surface that winds around a central point in a spiral pattern.",
        "A spiralled surface looks like a surface that has been wrapped around a cylinder or cone.",
        "A \"spiralled\" surface looks like a series of concentric circles that get progressively smaller as they get closer to the center of the spiral.",
        "A spiralled surface looks like a surface that has been wrapped around a spiral.",
        "A spiralled surface looks like a surface with a lot of twists and turns.",
        "A spiralled surface looks like a series of spirals or coils.",
        "A spiralled surface looks like a surface that has been wrapped around a cylinder or cone.",
        "A \"spiralled\" surface looks like a series of spirals or coils.",
        "A spiraled surface is a surface that has been twisted or curled so that it forms a spiral shape."
    ],
    "knitted": [
        "Knitted fabric is made up of interlocking loops of yarn or thread.",
        "Knitted material is usually made of two types of thread: the warp and weft.",
        "A knitted fabric is one that is produced by interlocking loops of yarn.",
        "Knitted fabric has a series of loops that are interlocked together.",
        "Knitted material has a textured surface with small V-shaped ridges.",
        "Knitted material looks like a series of loops that have been created by interlocking yarn.",
        "Knitted material is made up of interlocking loops of yarn or thread.",
        "Knitted fabric is created by interlocking loops of yarn.",
        "\"Knitted\" material is made up of small loops of thread that are interlocked together.",
        "Knitted material typically has a grid-like appearance with raised ridges running vertically and horizontally.",
        "A knitted surface has a textured, three-dimensional look.",
        "If you imagine a fabric made of interlocking loops of yarn, that is what a knitted surface looks like.",
        "A knitted surface can look like a fabric made up of interlocking loops of yarn.",
        "A \"knitted\" surface is a surface that is made up of small loops of yarn.",
        "A knitted surface is a surface that has been made by interlocking loops of yarn or thread.",
        "A \"knitted\" surface looks like a series of small loops that have been connected together.",
        "A knitted surface has a textured, bumpy surface.",
        "A knitted surface has a series of raised ridges and indentations that resemble the stitches of a knit fabric.",
        "A knitted surface has a series of small loops that are interconnected.",
        "A knitted surface typically has a series of interlocking loops that have been created by using a knitting needle."
    ],
    "grooved": [
        "Here is an image of what \"grooved\" material looks like:.",
        "A grooved surface has parallel lines cut into it.",
        "Grooved materials have ridges or lines running along their surface.",
        "A material that is \"grooved\" has indentations or furrows on its surface.",
        "A grooved material has parallelly spaced furrows or channels on its surface.",
        "Grooved material has parallel lines cut into it, usually for the purpose of decoration or to create a rougher surface.",
        "The term \"grooved\" can refer to many different types of surfaces or textures.",
        "Grooves are usually long and narrow, like a trench.",
        "A grooved material has a series of parallel ridges running along its surface.",
        "\"Grooved\" material is characterized by having one or more grooves running along its length.",
        "A grooved surface is formed when a hard object is dragged across a soft material, leaving a channel behind it.",
        "A grooved surface is a surface that has ridges or furrows cut into it.",
        "A grooved surface usually has parallel, linear scratches running across it.",
        "A grooved surface has a series of parallel lines cut into it.",
        "A grooved surface has a line or furrow cut into it.",
        "A grooved surface is a surface with a series of parallel lines running along it.",
        "A grooved surface has a series of evenly spaced, parallel indentations in it.",
        "A grooved surface is a surface that has been marked with fine lines.",
        "A grooved surface usually has parallel lines cut into it.",
        "A \"grooved\" surface looks like a surface with grooves in it."
    ],
    "dotted": [
        "Dotted material generally consists of small circles or dots that are printed or embroidered onto the fabric.",
        "Dottedmaterial typically has a textured surface with small bumps or ridges.",
        "Dotted material typically has small raised dots on the surface.",
        "Dotted material has small, raised dots on the surface.",
        "Dotted material typically has a series of small dots printed on it.",
        "A dotted material has small dots all over it.",
        "A dotted material has small dots all over it.",
        "A dotted material has a pattern of small dots.",
        "Dotted material is material that has small dots on it.",
        "Dotted material has small, raised dots on the surface.",
        "A dotted surface looks like a surface with dots on it.",
        "A dotted surface looks like it has a lot of small dots on it.",
        "A \"dotted\" surface looks like a surface that has been covered in dots.",
        "A dotted surface is a surface that is covered in dots.",
        "A dotted surface has a series of dots on it, rather than a solid color or pattern.",
        "A surface that is dotted looks like it has a lot of small bumps or pits.",
        "A dotted surface is a surface that has small, raised dots.",
        "A dotted surface is a surface with a lot of small bumps on it.",
        "A dotted surface has a texture that is bumpy and has small raised dots.",
        "A dotted surface looks like a surface with small dots on it."
    ],
    "interlaced": [
        "Interlaced material is made up of a series of parallel lines that are crossed by a series of perpendicular lines.",
        "Interlaced images appear as a series of scan lines.",
        "Interlaced material is a material that is made up of two or more different types of materials that are interwoven together.",
        "Interlaced material looks like a series of horizontal lines that are slightly offset from each other.",
        "\"Interlaced\" material is a video signal that is composed of two fields captured at slightly different times.",
        "Interlaced material is a type of digital video that appears to have scan lines.",
        "\"Interlaced\" material looks like a series of horizontal lines that are slightly offset from each other.",
        "Interlaced materials have a visible striped pattern.",
        "The alternate scanning of odd and even lines in an interlaced video signal.",
        "Interlaced material appears to have a series of curved lines running through it.",
        "A interlaced surface looks like a series of parallel lines.",
        "A interlaced surface has a surface that is not smooth, but instead has a series of ridges and valleys.",
        "A \"interlaced\" surface looks like two pieces of paper that have been glued together at the edges.",
        "A surface that is interlaced looks like a series of parallel lines that are crossed by a series of other parallel lines at regular intervals.",
        "A \"interlaced\" surface has a series of ridges and furrows that give it a textured look.",
        "Interlaced surfaces have a wavy, disorderly appearance.",
        "An interlaced surface is a surface that has been divided into a number of small strips, which are then woven together.",
        "Interlaced surfaces have a wavy or zigzag appearance.",
        "A surface that is interlaced has a criss-crossing pattern.",
        "The surface of an object that has been interlaced looks like it has been woven together."
    ],
    "crosshatched": [
        "A crosshatched material has a pattern of criss-crossed lines.",
        "Crosshatched fabric is a fabric that has a design made up of crossed lines.",
        "Crosshatched material is made up of a series of intersecting lines, usually in a criss-cross pattern.",
        "Crosshatched fabrics are materials which have two sets of perpendicular lines running over them.",
        "Crosshatched material is typically a fabric that has two different sets of parallel lines running in different directions.",
        "Crosshatched material has a series of parallel lines that intersect each other to form a diamond pattern.",
        "\"Crosshatched\" material usually has a pattern of repeated, intersecting lines.",
        "Crosshatched material has a texture that resembles a series of crossed lines.",
        " Crosshatched material has a series of parallel lines that intersect to form a diamond-like pattern.",
        "Crosshatched material typically has a pattern of parallel lines that intersect at right angles.",
        "A crosshatched surface is one that has a series of intersecting lines, giving it a criss-crossed appearance.",
        "A crosshatched surface looks like a surface with a series of parallel lines intersecting at right angles.",
        "A crosshatched surface looks like it has a lot of lines intersecting each other at different angles.",
        "Crosshatched surfaces are surfaces that have been covered with a series of intersecting lines.",
        "A crosshatched surface has a series of crossed lines running over it.",
        "A crosshatched surface is a surface that has been covered with a series of crossed lines.",
        "A crosshatched surface has a series of parallel lines that intersect each other at right angles.",
        "A crosshatched surface has a series of intersecting diagonal lines.",
        "A crosshatched surface looks like it has a series of overlapping diagonal lines.",
        "A crosshatched surface is a surface that has been covered with a series of parallel lines that cross each other."
    ],
    "wrinkled": [
        "A wrinkled material looks like it has been folded or creased.",
        "Wrinkled material is material that is no longer smooth, but instead is creased or folded.",
        "A wrinkled piece of material typically has creases or folds in it.",
        "Wrinkled material looks like it has been crumpled up and then smoothed out again.",
        "Another word for wrinkled could be crumpled.",
        "Wrinkled material generally looks like it has been crumpled up.",
        "Wrinkled material is material that has been creased, folded, or twisted so that it is no longer smooth.",
        "Wrinkled material can look like a fabric that has been rumpled or crumpled.",
        "Wrinkled material is generally creased or folded.",
        " Wrinkled material looks like it has wrinkles.",
        "A wrinkled surface looks like a series of small hills and valleys.",
        "A \"wrinkled\" surface looks like it has small, raised bumps all over it.",
        "A \"wrinkled\" surface looks like a piece of fabric that has been bunched up and then smoothed out again.",
        "A wrinkled surface has a lot of small folds or ridges in it.",
        "A wrinkled surface usually looks like a piece of fabric that has been crumpled up.",
        "A wrinkled surface looks like a surface that has been folded or creased.",
        "A \"wrinkled\" surface looks like a surface that has a lot of small wrinkles or creases on it.",
        "A wrinkled surface looks like it has a lot of small bumps or ridges.",
        "A \"wrinkled\" surface looks like a piece of paper that has been crumpled up into a ball.",
        "A wrinkled surface is one that is not smooth, but has ridges or bumps."
    ],
    "smeared": [
        "\"Smeared\" material looks like a blur or a smear.",
        "\"Smeared\" material looks like it has been smeared with a substance.",
        "Smeared material is material that has been spread or smudged, often in a wet or messy way.",
        "A smeared material is usually a liquid or a very fine powder.",
        "A: Smeared material is usually liquid or gel-like in appearance.",
        "A smeared material would have a streaky or blurry appearance.",
        "\"Smeared\" material looks like it has been smeared or wiped across a surface.",
        "\"Smeared\" material usually looks like a blur or a streak.",
        "There is no definitive answer to this question since the appearance of smeared material will depend on the specific material that is being smeared as well as the conditions under which the smearing is taking place.",
        "\"Smeared\" material can look like streaks or smudges on a surface.",
        "A smeared surface is usually rough and uneven.",
        "A \"smeared\" surface looks like it has been covered with a thin layer of something.",
        "A smeared surface is one that is not smooth.",
        "A \"smeared\" surface is a surface that has had a solid material applied to it in a very thin layer.",
        "A smeared surface looks unusable and unappealing.",
        "A smeared surface has a thin, even coating of something.",
        "A \"smeared\" surface looks like a surface with a lot of smears on it.",
        "A smeared surface looks like a surface that has been blurred or unclear.",
        "A smeared surface looks like a surface that has been covered in a thin layer of something.",
        "A smeared surfaces looks like it has been rubbed with a dirty cloth."
    ],
    "striped": [
        "Striped material usually has alternating bands of color running horizontally or vertically.",
        "Striped material is usually a cotton fabric with vertical or horizontal stripes.",
        "Striped material is a type of fabric that has stripes of different colors or shades.",
        "A striped fabric has horizontal or vertical lines running through it.",
        "A striped fabric has parallel lines of different colors running the length of the fabric.",
        "A striped material typically has a repeating pattern of light and dark stripes.",
        "A striped pattern typically consists of repeated, regular lines that run perpendicular to each other.",
        "A striped fabric has lines running vertically or horizontally across it.",
        "A striped fabric has parallel lines of different colors going across it.",
        "A striped material has lines going horizontally or vertically across it.",
        "A striped surface has alternating light and dark stripes.",
        "A \"striped\" surface has parallel lines running across it.",
        "A striped surface looks like a surface that has stripes on it.",
        "A striped surface looks like a surface that has stripes on it.",
        "A \"striped\" surface has alternating bands of light and dark colors.",
        "A striped surface looks like a surface that has been divided into a series of vertical stripes.",
        "A striped surface has evenly spaced lines running across it.",
        "A striped surface is a surface that has stripes of different colors on it.",
        "A \"striped\" surface looks like a surface that has stripes on it.",
        "A \"striped\" surface has rows of alternating light and dark colors."
    ],
    "braided": [
        " Braided material is made up of three or more strands of fabric that have been braided together.",
        "A braided material has multiple strands of material that are interwoven together.",
        "A braid is a complex weaving pattern created by interlacing three or more strands of flexible material such as textile yarns, wire, or hair.",
        "Braided material is made up of three or more strands of fabric that have been interlaced together.",
        "A braided material is a type of fabric that has been woven together in a narrowd, interlacing pattern.",
        "Braided material is a type of fabric that is made by interlacing three or more strands of yarn or thread together.",
        "A \"braided\" material looks like a rope or cord that is made up of three or more strands of material that have been twisted together.",
        "Braided material looks like a series of interconnected loops.",
        " Braided materials look like interwoven strands of material.",
        "\"Braided\" material often looks like a series of intertwined ropes or strips of fabric.",
        "A braided surface has a series of ridges and valleys that look like braids.",
        "A braided surface can look like a series of interlocking loops, or it can look like a series of intersecting lines.",
        "A braided surface looks like a series of interlocking loops.",
        "A braided surface can look like a series of interlocking loops or like a series of twists and turns.",
        "A braided surface looks like a series of interlocking loops.",
        "A \"braided\" surface looks like a surface that has been torn apart and then put back together again in a way that is not smooth.",
        "A \"braided\" surface is a surface formed by intersecting lines that cross over each other.",
        "A braided surface has a series of ridges and valleys that look like a braid.",
        "A braided surface is made up of two or more surface that intersect each other.",
        "A braided surface looks like a surface that has been intersected by a series of curves."
    ],
    "freckled": [
        "Freckled material typically has small, dark spots on a light background.",
        "Freckled material looks like it has small brown spots all over it.",
        "Freckled material typically has small, dark spots on a light background.",
        "There is no definitive answer to this question as \"freckled\" can mean different things to different people.",
        "Freckled material can look like a material that has small brown spots on it.",
        "Freckled material looks like small spots or dots on the surface.",
        "Freckled material can look like any other type of material with small spots or discolorations.",
        "Freckled material is material that contains small, dark spots.",
        "\"Freckled\" material is usually a material with small brown or black spots on it.",
        "Materials that are freckled usually have small spots of color on them.",
        "A freckled surface looks like a surface that has small, dark spots on it.",
        "A \"freckled\" surface is one that has many small, dark spots.",
        "A \"freckled\" surface is one that is covered in small spots or patches.",
        "A freckled surface looks like a small, flat, brown spot.",
        "A freckled surface is covered in tiny spots.",
        "A \"freckled\" surface usually has a small, brownish spot on it.",
        "A freckled surface is one that is covered in small, brown spots.",
        "A freckled surface will appear to have small dots or spots on it.",
        "A freckled surface is one that is covered with small, brownish spots.",
        "A freckled surface is one that is covered in small spots."
    ],
    "cobwebbed": [
        "\"Cobwebbed\" material is usually covered in a layer of dust or spider webs.",
        "Cobwebbed material is usually old and dusty.",
        "Cobwebbed material is usually covered in dust.",
        "Cobwebbed material is material that is covered in cobwebs.",
        "The word \"cobwebbed\" is often used to describe a material that is covered in dust or small particles.",
        "Cobwebbed material is usually old and dusty.",
        "Cobwebbed material is covered with a thin layer of dust or debris.",
        "Cobwebbed material is usually covered in dust and often has a web-like pattern.",
        "Cobwebbed material is material that is covered in cobwebs.",
        "Cobwebbed material has a lot of small, spidery threads coming from it.",
        "A cobwebbed surface is usually covered in fine dust or lint.",
        "Cobwebbed surfaces are often dusty and have a lot of spiders webs on them.",
        "A surface that is \"cobwebbed\" is covered with a thin, delicate webbing, usually found in the corners of rooms or other places where spiders commonly build their webs.",
        "When a surface is covered in cobwebs, it looks like there are thin, delicate webs stretched across it.",
        "A \"cobwebbed\" surface is one that is covered in fine, spider-web like strands.",
        "A cobwebbed surface has a lot of small, thin pieces of dirt or dust on it that look like a spider's web.",
        "A cobwebbed surface is a surface that is covered in cobwebs.",
        "A \"cobwebbed\" surface is usually covered in dust and looks like a spider's web.",
        "A surface that is covered in cobwebs looks like it is covered in a thin, sticky spider web.",
        "A cobwebbed surface looks like it has very fine, delicate, spider webs on it."
    ],
    "honeycombed": [
        "Honeycombed material looks like a series of hexagonal cells that are all interconnected.",
        "Honeycombed material is material that is full of small holes, like a beehive.",
        "Honeycombed material is a material that has been formed into a series of small hexagonal cells.",
        "A honeycomb material is typically a lightweight paper or plastic that has a hexagonal cell shape.",
        "Honeycomb material is made up of a series of hexagonal cells that are stacked together.",
        "a.",
        "A honeycombed material looks like a series of hexagons or honeycombs.",
        "Honeycombed material looks like a series of hexagonal shapes laid out in a honeycomb pattern.",
        "A honeycombed material is one that has a lot of small, hexagonal holes in it, like a beehive.",
        "Honeycombed material is material that has been cut or drilled into thin sheets with a honeycomb-like pattern.",
        "A honeycombed surface looks like a series of hexagonal cells.",
        "A honeycombed surface looks like a beehive, with a series of hexagonal cells.",
        "A honeycombed surface is a surface that has been divided into a series of small, hexagonal cells.",
        "A honeycombed surface is a series of hexagonal shapes that are all interconnected.",
        "A honeycombed surface is one that has a lot of small holes in it, making it look like a piece of honeycomb.",
        "A \"honeycombed\" surface is defined as a surface with a series of small, hexagonal indentations.",
        "A honeycombed surface looks like a series of small hexagonal cells, similar in appearance to a honeycomb.",
        "A honeycombed surface typically contains small, hexagonal holes stacked close together.",
        "A honeycombed surface looks like a series of hexagonal cells or sectors.",
        "A surface with a honeycomb pattern has a series of hexagonal cells that are empty in the center."
    ],
    "woven": [
        "Woven material looks like a piece of fabric with a weave pattern.",
        "Woven material is made of threads that are woven together.",
        "Woven material is material that has been interlaced to form a fabric.",
        "Woven material is a type of fabric that is created by interlacing two sets of yarn or thread at right angles to each other.",
        "Woven fabric has a flat surface with no piles.",
        "The word \"woven\" typically refers to a fabric that is created by interlacing two sets of yarn or other material at right angles to each other.",
        "The definition of woven is \"to construct (a fabric, etc.",
        "The word \"woven\" is used to describe a type of fabric that is created by interlacing two sets of threads at right angles.",
        "A woven fabric has a smooth surface with no loops on the right side, and the wrong side has a series of small loops.",
        "A woven fabric has a \"right\" side and a \" wrong\" side.",
        "A woven surface has a series of crossing lines that form a mesh-like pattern.",
        "A woven surface is a textured surface that simulates the appearance of fabric.",
        "A woven surface is composed of intersecting perpendicular threads or wires.",
        "A woven surface has a pattern of interlocking loops, similar to a fabric.",
        "A woven surface is a surface that is made of a series of interlocking loops of thread.",
        "A woven surface is made up of a series of interlocking loops that form a close-knit surface.",
        "A woven surface looks like a mesh or netting.",
        "A \"woven\" surface is a flat surface that has been interlaced with a pattern of perpendicular threads.",
        "A woven surface has a series of interwoven threads or strips of material.",
        "A woven surface is a three-dimensional surface that is made up of a series of interconnected loops."
    ],
    "matted": [
        "The term \"matted\" typically refers to a material that is tangled, knotted, or otherwise stuck together in a clump.",
        "Matted material has a tangled, matted appearance.",
        "Something that is matted looks like it has been tangled or knotted together.",
        "A mat is a piece of material that is used to cover or protect a surface.",
        "Matted material is material that is tangled and stuck together.",
        "The word \"matted\" is often used to describe hair that is tangled and unkempt.",
        "Generally, matted material is clumped together, tangled, or otherwise stuck together in a way that makes it difficult to smooth out or separate.",
        "Matted material is usually tangled or tangled up.",
        "A material that is matted has a surface that is covered with a tangled mass of fibers, hair, or other debris.",
        "Matted material may appear to be tangled or entwined.",
        "A matted surface is one that is covered in a tangled mass of something, such as hair or fibers.",
        "A matted surface is one that has had its fibers tangled together, making it appear dull, flat, and fuzzy.",
        "A matted surface is a surface with a lot of small tangles in it.",
        "A matted surface is usually bumpy or uneven.",
        "A matted surface has a rough, Ken surface.",
        "A matted surface looks like it has been covered in a thick layer of something.",
        "A matted surface has a lot of small tangles.",
        "A matted surface is a surface that has a lot of texture.",
        "When a surface is matted, it has a rough, mat-like texture.",
        "A matted surface has a rougher texture than a smooth one."
    ],
    "zigzagged": [
        "Zigzagged material is material that has been bent or folded into a zigzag pattern.",
        "Zigzag patterns are usually found on fabrics with a tight weave, such as twill or poplin.",
        "Zigzag stitches are usually used to finish a raw edge and to prevent fabric from unraveling.",
        "Zigzag patterns are created when parallel lines are connected by diagonal lines.",
        "A \"zigzagged\" material would look like a material that has been cut into thin strips and then sewn together at an angle.",
        "Zigzagged materials are materials that have been cut or torn into a zigzag shape.",
        "Zigzagged material is material that has been folded or cut into a series of parallel lines that alternate between going in one direction and then going in the opposite direction.",
        "\"Zigzagged\" material is characterized by its sharp, angular corners.",
        "Zigzag patterns are created when two diagonal lines are intersected by a horizontal or vertical line.",
        "Zigzag patterns are created when lines are drawn that connect at sharp angles, rather than curves.",
        "A zigzagged surface is one that is not smooth, but instead has a series of peaks and valleys.",
        "A zigzagged surface looks like it has a lot of angular shapes sticking out from it.",
        "A \"zigzagged\" surface is one that is not flat, but has a series of peaks and valleys.",
        "A zigzagged surface is a surface that has a lot of angular corners or edges.",
        "A zigzagged surface looks like a surface that has been cut or ripped into smaller pieces that are then put back together in a zigzag pattern.",
        "A zigzag surface has a series of peaks and valleys that resemble a zigzag pattern.",
        "A zigzagged surface looks like a surface with a lot of small peaks and valleys.",
        "A \"zigzagged\" surface has a series of sharp curves that alternate between going up and down.",
        "A zigzagged surface looks like a surface that has been cut into a series of angles.",
        "A zigzagged surface is one that has been cut or torn so that it is no longer smooth, but instead has a jagged edge."
    ],
    "marbled": [
        "Marbled material typically has a swirled or mottled appearance, as if different colors or types of material have been combined together.",
        "\"Marbled\" material is usually stained or discolored in a blotchy or streaked pattern.",
        "Marbled material usually has a streaked or clouded appearance, like marble.",
        "Marbled material is marked with patterns that look like veins or streaks in marble.",
        "Material that is marbled looks like it has been swirled together, creating a pattern that is similar to marble.",
        "In general, \"marbled\" material has a streaked or mottled appearance, like that of marble.",
        "Marbled material is material that has a smooth, shiny surface with a pattern that looks like it was created by swirling different colors of paint together.",
        "A material that is \"marbled\" is usually streaky or mottled in appearance.",
        "What does \"marbled\" material look like?Marbled materials have a streaked or mottled appearance, like that of a marble.",
        "Marbled material often looks like swirls of two colors.",
        "A marbled surface is one that has been marked with swirls or veins of color to resemble marble.",
        "A marbled surface is a surface with a pattern that looks like it was made by swirling different colors of paint or ink together.",
        "Marbled surfaces are usually found in nature and are created when two different colors of rock are layered on top of each other and then carved or cut into.",
        "A marbled surface looks like it has been covered in paint and then swirls have been added to create a marble effect.",
        "A marbled surface has a smooth, even surface with a slight swirl pattern.",
        "Amarbling is a spatter painting technique.",
        "A marbled surface has a smooth, flat surface with a design that appears to be swirled or mottled.",
        "Marbling is a pattern with a swirled or mottled appearance.",
        "A marbled surface has a swirled or streaked appearance, like that of marble.",
        "Marbling is a pattern of swirls and streaks in a material, usually caused by the mixed colors of a fluid."
    ],
    "studded": [
        "A studded material is one that has had small, metal studs affixed to it.",
        "Studded material is a material that has studs on it.",
        " leather that has metal spikes sticking out of it.",
        "Studded material typically has small metal ornaments embedded in it.",
        "\"Studded\" material normally refers to fabric that has had metal studs affixed to it in a decorative pattern.",
        "Studded material is typically a leather or fabric material that has metal studs affixed to it in a decorative manner.",
        "Studded material typically has small metal or plastic studs affixed to the surface.",
        "Studded material often looks like it has metal spikes sticking out of it.",
        "Studded material is material that has small, metal studs on it.",
        "A studded material typically has small metal studs or spikes adorning the surface.",
        "A studded surface should have a uniform grid of evenly-spaced raised bumps.",
        "A \"studded\" surface is one that has been covered with small projecting objects.",
        "A studded surface is covered in small, sharp protrusions.",
        "A studded surface is a surface that has small, raised bumps.",
        "A studded surface has small, raised bumps.",
        "Sadie has no studs.",
        "Studded surfaces have metal studs that provide traction in winter weather.",
        "A studded surface is covered in small, pointed objects.",
        "A studded surface is a surface that has a lot of small raised bumps on it.",
        "Image result for STUDDED SURFACE."
    ],
    "grid": [
        "\"Grid\" material is typically a black, plastic material that has a honeycomb-type structure.",
        "A material with a grid pattern has a series of parallel lines that cross each other to form a regular pattern.",
        "Grid material is a type of fabric that has a grid-like pattern.",
        "Grid material is a type of material that is often used in construction.",
        "\"Grid\" material can vary in appearance, but is typically a series of intersecting lines or a honeycomb-like pattern.",
        "In general, grid material is a network of uniformly spaced horizontal and vertical bars that are used to support or reinforce other materials.",
        "A grid pattern is a repeating, evenly spaced set of lines that intersect each other to form a series of squares or rectangles.",
        "Grid material looks like a network of squares.",
        "Most grid materials are made from some sort of plastic, and they have a bunch of small square or rectangular openings running through them.",
        "The grid material is placed over the opening in the window.",
        "A grid surface is like a checkered board.",
        "A grid surface is a surface that contains a series of evenly spaced horizontal and vertical lines.",
        "A grid surface looks like a checkerboard.",
        "A grid surface looks like a series of evenly spaced, parallel lines that intersect at right angles.",
        "A grid surface is usually a perpendicular array of lines, typically on a graph paper.",
        "A grid surface can look like a series of squares or a series of intersecting lines.",
        "A \"grid\" surface can look like a checkerboard, with squares of different colors or shades.",
        "Image result for grid surface.",
        "A grid surface has evenly spaced lines running horizontally and vertically.",
        "A \"grid\" surface looks like a set of evenly spaced horizontal and vertical lines that intersect to form squares."
    ]
}